### ISSUE TITLE
Marked drop in uploads for the past ~5 weeks?

### ISSUE THREAD

**Issue by misaochan** [whym/commons-app-stats#4] opened 2018-06-26 14:13 UTC
I noticed that there was a marked drop in uploads for the past ~5 wks (from ~500/wk to <100/wk). Do you know if there might be an error in the data collection @whym ? If not (and therefore the drop is accurate), I will need to take a look at why the uploads have dropped so much.

Thanks!

**Comment by whym** [comment] 2018-06-26 22:58
Thank for noticing that. After some digging, it looks like it was caused by a change in upload summary https://github.com/commons-app/apps-android-commons/commit/daf13935d16a191c0337b2761fbda7892580e6e4 - was the change included in a release approximately 5 weeks ago?

The stats tool finds mobile app uploads by pattern match. I will try fixing the regex.

**Comment by whym** [comment] 2018-06-27 07:40
I think the detection regex is now fixed. Sorry for the inaccuracies. On a brighter note, it looks like 2018Q2 was a record high quarter.
![latest_quarter](https://user-images.githubusercontent.com/10674/41959646-8baf4a8e-7a28-11e8-8f16-f96b6cfeb98f.png)

**Comment by misaochan** [comment] 2018-06-27 11:07
Oh, nice, thanks! Yeah, there was an upload summary change in the last release. Guess I was worrying for no reason, haha. :)

**Closed** 2018-06-27 11:08 UTC
